Feature/algo doa
sonia-auv/proc_hydrophone pull request #15
Opened 2022-07-15 18:18 UTC by sonia-dummy

**Warning :** Before creating a pull request, make sure that it does not already exists in the [pull requests](../). Thank you.

## Description
add the doa algo of the PFE of 2020

## How has this been tested ?
tested locally with bags

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2022-07-15 19:42 UTC, Kam0ss requested changes
Change sonia_common base image

2022-07-15 19:42 UTC, Kam0ss commented on Dockerfile
> +ARG BASE_IMAGE="ghcr.io/sonia-auv/sonia_common/sonia_common:x86-perception-feature-missing-info-hydro"
Should be back to latest since the merge is done in sonia_common.

2022-07-18 15:40 UTC, ACanadianMoose submitted a review, later dismissed

2022-07-19 22:17 UTC, Kam0ss approved these changes

2022-07-19 22:20 UTC, merged